### PR TITLE
Stringify Numeric, TrueClass and FalseClass types on render

### LINKED ISSUE #2: Stringify numbers, true, and false values
At the moment xml generation from such types is failing. I'll submit PR. This issue is just a reminder for me.

### PR DESCRIPTION
**Pull request by Bonias**
resolves #2

### CODE REVIEW

File: test/tox_test.rb [hunk 1]
```diff
@@ -426,6 +426,46 @@ def test_render_with_additional_attributes
...
+  def test_render_numeric
+    test_case_render(
+      %{
+        <profile>
+          <age>31</age>
+          <points>12.34</points>
+        </profile>
+      },
+      {
+        age:    '31',
```
Comment (challengee) [inline test/tox_test.rb]: your probably meant for this to be numeric instead of string?

Comment (Bonias) [inline test/tox_test.rb]: Fixed
